# 替换以下：
# var_svc：具体服务名，如gateway、user
# var_env：环境变量，如dev、beta、prod

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: var_svc
  labels:
    helm.sh/chart: go-svc-0.1.0
    app.kubernetes.io/name: go-svc
    app.kubernetes.io/instance: var_svc
    app.kubernetes.io/version: "1.0.0"
automountServiceAccountToken: true

---
apiVersion: v1
kind: Service
metadata:
  name: var_svc
  labels:
    helm.sh/chart: go-svc-0.1.0
    app.kubernetes.io/name: go-svc
    app.kubernetes.io/instance: var_svc
    app.kubernetes.io/version: "1.0.0"
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: go-svc
    app.kubernetes.io/instance: var_svc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: var_svc
  labels:
    helm.sh/chart: go-svc-0.1.0
    app.kubernetes.io/name: go-svc
    app.kubernetes.io/instance: var_svc
    app.kubernetes.io/version: "1.0.0"
    cc-lang: go # 所有自定义标签的前缀是 `cc-`
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: go-svc
      app.kubernetes.io/instance: var_svc
  template:
    metadata:
      labels:
        cc-name: var_svc
        app.kubernetes.io/name: go-svc
        app.kubernetes.io/instance: var_svc
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: var_svc
      securityContext:
        { }
      containers:
        - name: svc
          securityContext:
            { }
          image: docker.io/leigg/var_svc:1.0.0
          imagePullPolicy: Always
          env:
            - name: MICRO_SVC_ENV
              value: var_env
          ports:
            - name: grpc
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8000
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
