# 存放user相关配置，db信息配置到根目录的deploy/
root:
  svc: user
  log_level: debug
  disable_cache: true # 本地开发，禁用缓存功能（直读DB），免去缓存干扰问题

auth:
  token_expiry: "0" # 增加app端后要使用自动续期策略

open_sign_in_rate_limit: false
open_sign_up_rate_limit: false

default_assets:
  avatar: uploads/FBT_Avatar/default/111.png

# 三方登录支持
oauth_support:
  github:
    client_id: 0f0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d
    client_secret: 0f0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d
    redirect_uri: https://www.cocktailhack.io/oauth/callback?from=github