# 管理后台图片地址前缀
admin_system:
  img_base_url: https://admin.example.io/api

official_site:
  base_url: https://www.example.io

api_gateway:
  base_url: https://api.example.io

stripe:
  key: sk_live_xxx
